import type { JsonSchema } from './json-schema.js';
import {
  closeMonthRequestSchema,
  dailyRequestListSchema,
  dailyRequestSchema,
  decideDailyRequestRequestSchema,
  listDailyRequestsQuerySchema,
  listMonthlyClosingsQuerySchema,
  monthlyClosingListSchema,
  monthlyClosingSchema,
  reopenMonthRequestSchema,
  submitDailyRequestRequestSchema,
} from './schemas/approval.js';
import {
  assignmentContractListSchema,
  assignmentContractSchema,
  createAssignmentContractRequestSchema,
  createEmployeeAssignmentRequestSchema,
  employeeAssignmentListSchema,
  employeeAssignmentSchema,
  endEmployeeAssignmentRequestSchema,
  grantUserScopeRequestSchema,
  userScopeListSchema,
  userScopeSchema,
} from './schemas/assignment.js';
import {
  correctAttendanceRequestSchema,
  correctAttendanceResponseSchema,
  recordAttendanceEventRequestSchema,
  recordAttendanceEventResponseSchema,
  workDaySchema,
} from './schemas/attendance.js';
import {
  anomalyListSchema,
  auditLogListSchema,
  listAnomaliesQuerySchema,
} from './schemas/audit.js';
import {
  changePasswordRequestSchema,
  loginRequestSchema,
  resetUserPasswordRequestSchema,
  revokedSessionsSchema,
  revokedUserSessionsSchema,
  sessionListSchema,
  sessionResponseSchema,
  updatePreferencesRequestSchema,
} from './schemas/auth.js';
import {
  cardCredentialListSchema,
  cardCredentialSchema,
  cardEventRequestSchema,
  cardEventResponseSchema,
  createCardRegistrationRequestSchema,
  createCardRegistrationResponseSchema,
  registerCardRequestSchema,
} from './schemas/card.js';
import { businessDateSchema, errorResponseSchema, uuidSchema } from './schemas/common.js';
import {
  deviceEventRequestSchema,
  deviceEventResponseSchema,
  deviceListSchema,
  deviceReceiptListSchema,
  deviceSchema,
  enrollDeviceRequestSchema,
  enrollDeviceResponseSchema,
  registerDeviceRequestSchema,
  registerDeviceResponseSchema,
} from './schemas/device.js';
import {
  createRequestTypeRequestSchema,
  decideEmployeeRequestRequestSchema,
  employeeRequestListSchema,
  employeeRequestSchema,
  listEmployeeRequestsQuerySchema,
  requestTypeListSchema,
  requestTypeSchema,
  resubmitEmployeeRequestRequestSchema,
  submitEmployeeRequestRequestSchema,
  updateRequestTypeRequestSchema,
} from './schemas/employee-request.js';
import {
  abandonedDeliveryListSchema,
  apiKeyListSchema,
  apiKeySchema,
  createApiKeyRequestSchema,
  createApiKeyResponseSchema,
  createWebhookEndpointRequestSchema,
  createWebhookEndpointResponseSchema,
  employeeImportCsvSchema,
  exportAttendanceQuerySchema,
  exportPayrollQuerySchema,
  importResultSchema,
  webhookDeliveryListSchema,
  webhookEndpointListSchema,
} from './schemas/integration.js';
import {
  createLaborSystemAssignmentRequestSchema,
  endLaborSystemAssignmentRequestSchema,
  laborSystemAssignmentListSchema,
  laborSystemAssignmentSchema,
} from './schemas/labor-system.js';
import {
  adjustLeaveRequestSchema,
  grantLeaveRequestSchema,
  leaveBalanceListSchema,
  leaveLedgerEntrySchema,
  leaveLedgerListSchema,
  leaveTypeSettingsListSchema,
  leaveTypeSettingsSchema,
  listLeaveBalancesQuerySchema,
  listLeaveLedgerQuerySchema,
  reverseLeaveEntryRequestSchema,
  updateLeaveTypeRequestSchema,
} from './schemas/leave.js';
import {
  closingReadinessListSchema,
  listMonthlySummariesQuerySchema,
  listPeriodSummariesQuerySchema,
  monthlySummaryListSchema,
  periodSummaryListSchema,
  recalculateAttendanceRequestSchema,
  recalculateAttendanceResponseSchema,
} from './schemas/monthly.js';
import {
  createDepartmentRequestSchema,
  createEmployeeRequestSchema,
  createOrganizationRequestSchema,
  createSiteRequestSchema,
  departmentListSchema,
  departmentSchema,
  employeeListSchema,
  employeeSchema,
  organizationListSchema,
  organizationSchema,
  siteListSchema,
  siteSchema,
} from './schemas/organization.js';
import {
  assignWorkCycleRequestSchema,
  createLeaveTypeRequestSchema,
  createWorkCycleRequestSchema,
  createWorkPatternRequestSchema,
  employeeWorkCycleListSchema,
  employeeWorkCycleSchema,
  endWorkCycleAssignmentRequestSchema,
  generateWorkSchedulesRequestSchema,
  generateWorkSchedulesResponseSchema,
  leaveTypeListSchema,
  leaveTypeSchema,
  listEmployeeWorkCyclesQuerySchema,
  listWorkSchedulesQuerySchema,
  upsertWorkScheduleRequestSchema,
  workCycleListSchema,
  workCycleSchema,
  workPatternListSchema,
  workPatternSchema,
  workScheduleListSchema,
  workScheduleSchema,
} from './schemas/schedule.js';
import {
  discrepancyReportSchema,
  getDiscrepancyReportQuerySchema,
  listSessionObservationsQuerySchema,
  recordSessionObservationsRequestSchema,
  recordSessionObservationsResponseSchema,
  sessionObservationListSchema,
} from './schemas/session.js';
import {
  calculationRuleVersionListSchema,
  calculationRuleVersionSchema,
  createCalculationRuleVersionRequestSchema,
  createWorkCategoryRequestSchema,
  workCategoryListSchema,
  workCategorySchema,
} from './schemas/work-category.js';

export type HttpMethod = 'get' | 'post' | 'patch' | 'put' | 'delete';

/** 認証方式。フェーズが進むにつれて API キーが加わる。 */
/**
 * 呼び出しに必要な資格。
 * `sessionOrApiKey` は、画面のセッションでも API キーでも呼べる経路を表す。
 */
export type SecurityRequirement = 'public' | 'session' | 'deviceSignature' | 'sessionOrApiKey';

export interface ResponseContract {
  status: number;
  description: string;
  schema?: JsonSchema;
}

export interface PathParameterContract {
  name: string;
  description: string;
  schema: JsonSchema;
}

export interface OperationContract {
  operationId: string;
  method: HttpMethod;
  /** OpenAPI 形式のパス（`/employees/{employeeId}`）。 */
  path: string;
  summary: string;
  tags: readonly string[];
  security: SecurityRequirement;
  pathParameters?: readonly PathParameterContract[];
  requestBody?: JsonSchema;
  /** 要求本文の内容種別。省略すると application/json。 */
  requestContentType?: string;
  /** 応答本文の内容種別。省略すると application/json。 */
  responseContentType?: string;
  query?: JsonSchema;
  responses: readonly ResponseContract[];
}

const unauthorized: ResponseContract = {
  status: 401,
  description: '認証されていない',
  schema: errorResponseSchema,
};
const forbidden: ResponseContract = {
  status: 403,
  description: '権限が不足している',
  schema: errorResponseSchema,
};
const invalidRequest: ResponseContract = {
  status: 400,
  description: '要求の内容が契約に合わない',
  schema: errorResponseSchema,
};
const conflict: ResponseContract = {
  status: 409,
  description: '既存のデータと衝突している',
  schema: errorResponseSchema,
};

export const operations = {
  login: {
    operationId: 'login',
    method: 'post',
    path: '/auth/login',
    summary: 'ローカル認証でログインし、セッションを開始する',
    tags: ['auth'],
    security: 'public',
    requestBody: loginRequestSchema,
    responses: [
      { status: 200, description: 'ログイン成功', schema: sessionResponseSchema },
      invalidRequest,
      { status: 401, description: '認証情報が一致しない', schema: errorResponseSchema },
    ],
  },
  logout: {
    operationId: 'logout',
    method: 'post',
    path: '/auth/logout',
    summary: '現在のセッションを失効させる',
    tags: ['auth'],
    security: 'public',
    responses: [{ status: 204, description: '失効済み' }],
  },
  getSession: {
    operationId: 'getSession',
    method: 'get',
    path: '/auth/session',
    summary: '現在のセッションと利用者情報を取得する',
    tags: ['auth'],
    security: 'session',
    responses: [
      { status: 200, description: '有効なセッション', schema: sessionResponseSchema },
      unauthorized,
    ],
  },
  changePassword: {
    operationId: 'changePassword',
    method: 'post',
    path: '/auth/password',
    summary: '現在のパスワードを確認したうえで、自分のパスワードを変更する',
    tags: ['auth'],
    security: 'session',
    requestBody: changePasswordRequestSchema,
    responses: [
      { status: 204, description: '変更済み。他のセッションは失効する' },
      invalidRequest,
      unauthorized,
    ],
  },
  listSessions: {
    operationId: 'listSessions',
    method: 'get',
    path: '/auth/sessions',
    summary: '自分の、まだ有効なセッションを一覧する',
    tags: ['auth'],
    security: 'session',
    responses: [
      { status: 200, description: '自分のセッションの一覧', schema: sessionListSchema },
      unauthorized,
    ],
  },
  revokeSession: {
    operationId: 'revokeSession',
    method: 'delete',
    path: '/auth/sessions/{sessionId}',
    summary: '自分のセッションを 1 件失効させる',
    tags: ['auth'],
    security: 'session',
    pathParameters: [{ name: 'sessionId', description: 'セッションの識別子', schema: uuidSchema }],
    responses: [
      { status: 204, description: '失効済み' },
      // いま使っているセッションは、この経路では終わらせない。ログアウトが担う。
      invalidRequest,
      unauthorized,
      { status: 404, description: '自分のセッションに見つからない', schema: errorResponseSchema },
    ],
  },
  revokeOtherSessions: {
    operationId: 'revokeOtherSessions',
    method: 'post',
    path: '/auth/sessions/revoke-others',
    summary: 'いま使っているセッション以外を、まとめて失効させる',
    tags: ['auth'],
    security: 'session',
    responses: [
      { status: 200, description: '失効させた件数', schema: revokedSessionsSchema },
      unauthorized,
    ],
  },
  updatePreferences: {
    operationId: 'updatePreferences',
    method: 'patch',
    path: '/auth/preferences',
    summary: '表示言語などの利用者設定を更新する',
    tags: ['auth'],
    security: 'session',
    requestBody: updatePreferencesRequestSchema,
    responses: [
      { status: 200, description: '更新後のセッション情報', schema: sessionResponseSchema },
      invalidRequest,
      unauthorized,
    ],
  },
  listOrganizations: {
    operationId: 'listOrganizations',
    method: 'get',
    path: '/organizations',
    summary: '組織の一覧を取得する',
    tags: ['organization'],
    security: 'session',
    responses: [
      { status: 200, description: '組織の一覧', schema: organizationListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createOrganization: {
    operationId: 'createOrganization',
    method: 'post',
    path: '/organizations',
    summary: '組織を登録する',
    tags: ['organization'],
    security: 'session',
    requestBody: createOrganizationRequestSchema,
    responses: [
      { status: 201, description: '登録した組織', schema: organizationSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
    ],
  },
  listSites: {
    operationId: 'listSites',
    method: 'get',
    path: '/sites',
    summary: '拠点の一覧を取得する',
    tags: ['organization'],
    security: 'session',
    responses: [
      { status: 200, description: '拠点の一覧', schema: siteListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createSite: {
    operationId: 'createSite',
    method: 'post',
    path: '/sites',
    summary: '拠点を登録する',
    tags: ['organization'],
    security: 'session',
    requestBody: createSiteRequestSchema,
    responses: [
      { status: 201, description: '登録した拠点', schema: siteSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
    ],
  },
  listDepartments: {
    operationId: 'listDepartments',
    method: 'get',
    path: '/departments',
    summary: '部門の一覧を取得する',
    tags: ['organization'],
    security: 'session',
    responses: [
      { status: 200, description: '部門の一覧', schema: departmentListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createDepartment: {
    operationId: 'createDepartment',
    method: 'post',
    path: '/departments',
    summary: '部門を登録する',
    tags: ['organization'],
    security: 'session',
    requestBody: createDepartmentRequestSchema,
    responses: [
      { status: 201, description: '登録した部門', schema: departmentSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
    ],
  },
  listEmployees: {
    operationId: 'listEmployees',
    method: 'get',
    path: '/employees',
    summary: '従業員の一覧を取得する',
    tags: ['employee'],
    security: 'session',
    responses: [
      { status: 200, description: '従業員の一覧', schema: employeeListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createEmployee: {
    operationId: 'createEmployee',
    method: 'post',
    path: '/employees',
    summary: '従業員を登録する（任意でログイン用の利用者も作成する）',
    tags: ['employee'],
    security: 'session',
    requestBody: createEmployeeRequestSchema,
    responses: [
      { status: 201, description: '登録した従業員', schema: employeeSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
    ],
  },
  recordAttendanceEvent: {
    operationId: 'recordAttendanceEvent',
    method: 'post',
    path: '/attendance/events',
    summary: '自分の打刻を記録する（同じ冪等キーの再送は 1 件だけ記録される）',
    tags: ['attendance'],
    security: 'session',
    requestBody: recordAttendanceEventRequestSchema,
    responses: [
      {
        status: 201,
        description: '記録した打刻とその日の状態',
        schema: recordAttendanceEventResponseSchema,
      },
      {
        status: 200,
        description: '同じ冪等キーの再送。既存の記録をそのまま返す',
        schema: recordAttendanceEventResponseSchema,
      },
      invalidRequest,
      unauthorized,
      forbidden,
      {
        status: 409,
        description: '現在の状態では受け付けられない打刻',
        schema: errorResponseSchema,
      },
    ],
  },
  getTodayAttendance: {
    operationId: 'getTodayAttendance',
    method: 'get',
    path: '/attendance/today',
    summary: '自分の当日の勤務状態と打刻を取得する',
    tags: ['attendance'],
    security: 'session',
    responses: [
      { status: 200, description: '当日の勤務状態', schema: workDaySchema },
      unauthorized,
      forbidden,
    ],
  },
  getAttendanceDay: {
    operationId: 'getAttendanceDay',
    method: 'get',
    path: '/attendance/days/{businessDate}',
    summary: '自分の指定した業務日の勤務状態と、修正を含むすべての記録を取得する',
    tags: ['attendance'],
    security: 'session',
    pathParameters: [
      { name: 'businessDate', description: '業務日（YYYY-MM-DD）', schema: businessDateSchema },
    ],
    responses: [
      { status: 200, description: '指定した業務日の勤務状態', schema: workDaySchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  correctAttendance: {
    operationId: 'correctAttendance',
    method: 'post',
    path: '/attendance/corrections',
    summary: '自分の打刻を修正する（元の打刻は書き換えず、修正イベントを追加する）',
    tags: ['attendance'],
    security: 'session',
    requestBody: correctAttendanceRequestSchema,
    responses: [
      {
        status: 201,
        description: '記録した修正とその日の状態',
        schema: correctAttendanceResponseSchema,
      },
      {
        status: 200,
        description: '同じ冪等キーの再送。既存の記録をそのまま返す',
        schema: correctAttendanceResponseSchema,
      },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '対象の打刻が見つからない', schema: errorResponseSchema },
    ],
  },
  listWorkCategories: {
    operationId: 'listWorkCategories',
    method: 'get',
    path: '/work-categories',
    summary: '勤務区分の版を一覧する',
    tags: ['schedule'],
    security: 'session',
    responses: [
      { status: 200, description: '勤務区分の一覧', schema: workCategoryListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createWorkCategory: {
    operationId: 'createWorkCategory',
    method: 'post',
    path: '/work-categories',
    summary: '勤務区分の版を作る',
    tags: ['schedule'],
    security: 'session',
    requestBody: createWorkCategoryRequestSchema,
    responses: [
      { status: 201, description: '作った勤務区分', schema: workCategorySchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
    ],
  },
  listCalculationRuleVersions: {
    operationId: 'listCalculationRuleVersions',
    method: 'get',
    path: '/calculation-rule-versions',
    summary: '計算規則の版を一覧する',
    tags: ['schedule'],
    security: 'session',
    responses: [
      { status: 200, description: '計算規則の版', schema: calculationRuleVersionListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createCalculationRuleVersion: {
    operationId: 'createCalculationRuleVersion',
    method: 'post',
    path: '/calculation-rule-versions',
    summary: '計算規則の版を作る',
    tags: ['schedule'],
    security: 'session',
    requestBody: createCalculationRuleVersionRequestSchema,
    responses: [
      { status: 201, description: '作った版', schema: calculationRuleVersionSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
    ],
  },
  listLaborSystemAssignments: {
    operationId: 'listLaborSystemAssignments',
    method: 'get',
    path: '/labor-system-assignments',
    summary: '労働形態の割当を一覧する',
    tags: ['schedule'],
    security: 'session',
    query: listEmployeeWorkCyclesQuerySchema,
    responses: [
      { status: 200, description: '割当の一覧', schema: laborSystemAssignmentListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  assignLaborSystem: {
    operationId: 'assignLaborSystem',
    method: 'post',
    path: '/labor-system-assignments',
    summary: '労働形態を割り当てる',
    tags: ['schedule'],
    security: 'session',
    requestBody: createLaborSystemAssignmentRequestSchema,
    responses: [
      { status: 201, description: '作った割当', schema: laborSystemAssignmentSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
    ],
  },
  endLaborSystemAssignment: {
    operationId: 'endLaborSystemAssignment',
    method: 'post',
    path: '/labor-system-assignments/{laborSystemAssignmentId}/end',
    summary: '労働形態の割当へ終了日を設定する',
    tags: ['schedule'],
    security: 'session',
    pathParameters: [
      { name: 'laborSystemAssignmentId', description: '割当の識別子', schema: uuidSchema },
    ],
    requestBody: endLaborSystemAssignmentRequestSchema,
    responses: [
      { status: 200, description: '終了日を設定した割当', schema: laborSystemAssignmentSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '割当が見つからない', schema: errorResponseSchema },
      conflict,
    ],
  },
  listWorkPatterns: {
    operationId: 'listWorkPatterns',
    method: 'get',
    path: '/work-patterns',
    summary: '勤務パターンの一覧を取得する',
    tags: ['schedule'],
    security: 'session',
    responses: [
      { status: 200, description: '勤務パターンの一覧', schema: workPatternListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createWorkPattern: {
    operationId: 'createWorkPattern',
    method: 'post',
    path: '/work-patterns',
    summary: '勤務パターンを登録する',
    tags: ['schedule'],
    security: 'session',
    requestBody: createWorkPatternRequestSchema,
    responses: [
      { status: 201, description: '登録した勤務パターン', schema: workPatternSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
    ],
  },
  listWorkSchedules: {
    operationId: 'listWorkSchedules',
    method: 'get',
    path: '/work-schedules',
    summary: '指定した従業員・期間の勤務予定を取得する',
    tags: ['schedule'],
    security: 'session',
    query: listWorkSchedulesQuerySchema,
    responses: [
      { status: 200, description: '勤務予定の一覧', schema: workScheduleListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  upsertWorkSchedule: {
    operationId: 'upsertWorkSchedule',
    method: 'put',
    path: '/work-schedules',
    summary: '勤務予定を登録・更新する',
    tags: ['schedule'],
    security: 'session',
    requestBody: upsertWorkScheduleRequestSchema,
    responses: [
      { status: 200, description: '登録した勤務予定', schema: workScheduleSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      {
        status: 404,
        description: '従業員または勤務パターンが見つからない',
        schema: errorResponseSchema,
      },
    ],
  },
  submitDailyRequest: {
    operationId: 'submitDailyRequest',
    method: 'post',
    path: '/attendance/requests',
    summary: '自分の日次勤怠を申請する（差し戻された申請の再提出も同じ操作）',
    tags: ['approval'],
    security: 'session',
    requestBody: submitDailyRequestRequestSchema,
    responses: [
      { status: 200, description: '提出後の申請', schema: dailyRequestSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 409, description: '現在の状態では提出できない', schema: errorResponseSchema },
    ],
  },
  listDailyRequests: {
    operationId: 'listDailyRequests',
    method: 'get',
    path: '/attendance/requests',
    summary: '日次申請を一覧する（従業員を指定しない場合は承認対象を返す）',
    tags: ['approval'],
    security: 'session',
    query: listDailyRequestsQuerySchema,
    responses: [
      { status: 200, description: '申請の一覧', schema: dailyRequestListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  approveDailyRequest: {
    operationId: 'approveDailyRequest',
    method: 'post',
    path: '/attendance/requests/{requestId}/approve',
    summary: '日次申請を承認する',
    tags: ['approval'],
    security: 'session',
    pathParameters: [{ name: 'requestId', description: '申請の識別子', schema: uuidSchema }],
    requestBody: decideDailyRequestRequestSchema,
    responses: [
      { status: 200, description: '承認後の申請', schema: dailyRequestSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '申請が見つからない', schema: errorResponseSchema },
      { status: 409, description: '現在の状態では承認できない', schema: errorResponseSchema },
    ],
  },
  returnDailyRequest: {
    operationId: 'returnDailyRequest',
    method: 'post',
    path: '/attendance/requests/{requestId}/return',
    summary: '日次申請を差し戻す（理由のコメントが必須）',
    tags: ['approval'],
    security: 'session',
    pathParameters: [{ name: 'requestId', description: '申請の識別子', schema: uuidSchema }],
    requestBody: decideDailyRequestRequestSchema,
    responses: [
      { status: 200, description: '差し戻し後の申請', schema: dailyRequestSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '申請が見つからない', schema: errorResponseSchema },
      { status: 409, description: '現在の状態では差し戻せない', schema: errorResponseSchema },
    ],
  },
  cancelDailyRequest: {
    operationId: 'cancelDailyRequest',
    method: 'post',
    path: '/attendance/requests/{requestId}/cancel',
    summary: '自分の日次申請を取り消す',
    tags: ['approval'],
    security: 'session',
    pathParameters: [{ name: 'requestId', description: '申請の識別子', schema: uuidSchema }],
    requestBody: decideDailyRequestRequestSchema,
    responses: [
      { status: 200, description: '取消後の申請', schema: dailyRequestSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '申請が見つからない', schema: errorResponseSchema },
      { status: 409, description: '現在の状態では取り消せない', schema: errorResponseSchema },
    ],
  },
  listMonthlyClosings: {
    operationId: 'listMonthlyClosings',
    method: 'get',
    path: '/monthly-closings',
    summary: '月次締めの状態を一覧する',
    tags: ['approval'],
    security: 'session',
    query: listMonthlyClosingsQuerySchema,
    responses: [
      { status: 200, description: '締めの一覧', schema: monthlyClosingListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  closeMonth: {
    operationId: 'closeMonth',
    method: 'post',
    path: '/monthly-closings/close',
    summary: '指定した従業員・期間の月次締めを行う',
    tags: ['approval'],
    security: 'session',
    requestBody: closeMonthRequestSchema,
    responses: [
      { status: 200, description: '締めた期間', schema: monthlyClosingSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      {
        status: 409,
        description: '未承認の申請が残っている、またはすでに締め済み',
        schema: errorResponseSchema,
      },
    ],
  },
  reopenMonth: {
    operationId: 'reopenMonth',
    method: 'post',
    path: '/monthly-closings/reopen',
    summary: '月次締めを解除する（理由が必須）',
    tags: ['approval'],
    security: 'session',
    requestBody: reopenMonthRequestSchema,
    responses: [
      { status: 200, description: '解除した期間', schema: monthlyClosingSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      {
        status: 409,
        description: '締められていない期間は解除できない',
        schema: errorResponseSchema,
      },
    ],
  },
  listDevices: {
    operationId: 'listDevices',
    method: 'get',
    path: '/devices',
    summary: '打刻端末の一覧を取得する',
    tags: ['device'],
    security: 'session',
    responses: [
      { status: 200, description: '端末の一覧', schema: deviceListSchema },
      unauthorized,
      forbidden,
    ],
  },
  registerDevice: {
    operationId: 'registerDevice',
    method: 'post',
    path: '/devices',
    summary: '端末の枠を作り、一度きりの登録トークンを発行する',
    tags: ['device'],
    security: 'session',
    requestBody: registerDeviceRequestSchema,
    responses: [
      { status: 201, description: '登録トークンつきの端末', schema: registerDeviceResponseSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '拠点が見つからない', schema: errorResponseSchema },
    ],
  },
  revokeDevice: {
    operationId: 'revokeDevice',
    method: 'post',
    path: '/devices/{deviceId}/revoke',
    summary: '端末を失効させ、以後の署名イベントを受け付けないようにする',
    tags: ['device'],
    security: 'session',
    pathParameters: [{ name: 'deviceId', description: '端末の識別子', schema: uuidSchema }],
    responses: [
      { status: 200, description: '失効した端末', schema: deviceSchema },
      unauthorized,
      forbidden,
      { status: 404, description: '端末が見つからない', schema: errorResponseSchema },
      { status: 409, description: 'すでに失効している', schema: errorResponseSchema },
    ],
  },
  listDeviceReceipts: {
    operationId: 'listDeviceReceipts',
    method: 'get',
    path: '/devices/{deviceId}/receipts',
    summary: '端末から届いたイベントの受信記録を取得する',
    tags: ['device'],
    security: 'session',
    pathParameters: [{ name: 'deviceId', description: '端末の識別子', schema: uuidSchema }],
    responses: [
      { status: 200, description: '受信記録', schema: deviceReceiptListSchema },
      unauthorized,
      forbidden,
      { status: 404, description: '端末が見つからない', schema: errorResponseSchema },
    ],
  },
  enrollDevice: {
    operationId: 'enrollDevice',
    method: 'post',
    path: '/device-agent/enroll',
    summary: 'Agent が登録トークンと引き換えに公開鍵を登録する',
    tags: ['device'],
    security: 'public',
    requestBody: enrollDeviceRequestSchema,
    responses: [
      { status: 200, description: '登録した端末', schema: enrollDeviceResponseSchema },
      invalidRequest,
      { status: 401, description: '登録トークンが一致しない', schema: errorResponseSchema },
      {
        status: 409,
        description: 'すでに登録済み、失効している、または登録トークンが同時に使われた',
        schema: errorResponseSchema,
      },
    ],
  },
  recordDeviceEvent: {
    operationId: 'recordDeviceEvent',
    method: 'post',
    path: '/device-agent/events',
    summary: '端末が署名した打刻イベントを受け取る',
    tags: ['device'],
    security: 'deviceSignature',
    requestBody: deviceEventRequestSchema,
    responses: [
      { status: 201, description: '受理した打刻', schema: deviceEventResponseSchema },
      {
        status: 200,
        description: '同じ冪等キーの再送。受領記録に残した最初の応答をそのまま返す',
        schema: deviceEventResponseSchema,
      },
      invalidRequest,
      {
        status: 401,
        description: '署名が一致しない、または端末が有効でない',
        schema: errorResponseSchema,
      },
      { status: 404, description: '従業員が見つからない', schema: errorResponseSchema },
      {
        status: 409,
        description: '現在の状態では受け付けられない打刻。断った要求の再送も同じ理由で断る',
        schema: errorResponseSchema,
      },
    ],
  },
  listCardCredentials: {
    operationId: 'listCardCredentials',
    method: 'get',
    path: '/card-credentials',
    summary: 'IC カードの資格情報を一覧する（指紋は含めない）',
    tags: ['card'],
    security: 'session',
    responses: [
      { status: 200, description: '資格情報の一覧', schema: cardCredentialListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createCardRegistration: {
    operationId: 'createCardRegistration',
    method: 'post',
    path: '/card-credentials/registrations',
    summary: 'カード登録用の一度きりのトークンを発行する',
    tags: ['card'],
    security: 'session',
    requestBody: createCardRegistrationRequestSchema,
    responses: [
      {
        status: 201,
        description: '登録トークン',
        schema: createCardRegistrationResponseSchema,
      },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '従業員が見つからない', schema: errorResponseSchema },
    ],
  },
  revokeCardCredential: {
    operationId: 'revokeCardCredential',
    method: 'post',
    path: '/card-credentials/{cardCredentialId}/revoke',
    summary: 'IC カードの資格情報を失効させる',
    tags: ['card'],
    security: 'session',
    pathParameters: [
      { name: 'cardCredentialId', description: '資格情報の識別子', schema: uuidSchema },
    ],
    responses: [
      { status: 200, description: '失効した資格情報', schema: cardCredentialSchema },
      unauthorized,
      forbidden,
      { status: 404, description: '資格情報が見つからない', schema: errorResponseSchema },
      { status: 409, description: 'すでに失効している', schema: errorResponseSchema },
    ],
  },
  registerCard: {
    operationId: 'registerCard',
    method: 'post',
    path: '/device-agent/card-credentials',
    summary: 'Agent が読み取ったカードの指紋を登録トークンと結び付ける',
    tags: ['card'],
    security: 'deviceSignature',
    requestBody: registerCardRequestSchema,
    responses: [
      { status: 201, description: '登録した資格情報', schema: cardCredentialSchema },
      invalidRequest,
      {
        status: 401,
        description: '端末を認証できない、または登録トークンが一致しない',
        schema: errorResponseSchema,
      },
      {
        status: 409,
        description: 'このカードは別の従業員に登録されている、または登録トークンが同時に使われた',
        schema: errorResponseSchema,
      },
    ],
  },
  recordCardEvent: {
    operationId: 'recordCardEvent',
    method: 'post',
    path: '/device-agent/card-events',
    summary: '端末がカードの読み取りから作った打刻イベントを受け取る',
    tags: ['card'],
    security: 'deviceSignature',
    requestBody: cardEventRequestSchema,
    responses: [
      { status: 201, description: '受理した打刻', schema: cardEventResponseSchema },
      {
        status: 200,
        description: '同じ冪等キーの再送。受領記録に残した最初の応答をそのまま返す',
        schema: cardEventResponseSchema,
      },
      invalidRequest,
      { status: 401, description: '端末を認証できません', schema: errorResponseSchema },
      { status: 404, description: 'カードが登録されていない', schema: errorResponseSchema },
      {
        status: 409,
        description: '現在の状態では受け付けられない打刻。断った要求の再送も同じ理由で断る',
        schema: errorResponseSchema,
      },
    ],
  },
  recordSessionObservations: {
    operationId: 'recordSessionObservations',
    method: 'post',
    path: '/device-agent/session-observations',
    summary: '端末がまとめて送る PC セッションの観測を受け取る',
    tags: ['session'],
    security: 'deviceSignature',
    requestBody: recordSessionObservationsRequestSchema,
    responses: [
      {
        status: 201,
        description: '記録した観測',
        schema: recordSessionObservationsResponseSchema,
      },
      {
        status: 200,
        description: '同じ冪等キーの再送',
        schema: recordSessionObservationsResponseSchema,
      },
      invalidRequest,
      { status: 401, description: '端末を認証できません', schema: errorResponseSchema },
      {
        status: 409,
        description: '同じ端末で受理済みの連番以下が、別の冪等キーで送られた',
        schema: errorResponseSchema,
      },
    ],
  },
  listSessionObservations: {
    operationId: 'listSessionObservations',
    method: 'get',
    path: '/session-observations',
    summary: 'PC セッションの観測を一覧する',
    tags: ['session'],
    security: 'session',
    query: listSessionObservationsQuerySchema,
    responses: [
      { status: 200, description: '観測の一覧', schema: sessionObservationListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  getDiscrepancyReport: {
    operationId: 'getDiscrepancyReport',
    method: 'get',
    path: '/attendance/days/{businessDate}/discrepancies',
    summary: '指定した業務日の、打刻と PC 観測の食い違いを取得する',
    tags: ['session'],
    security: 'session',
    pathParameters: [
      { name: 'businessDate', description: '業務日（YYYY-MM-DD）', schema: businessDateSchema },
    ],
    query: getDiscrepancyReportQuerySchema,
    responses: [
      { status: 200, description: '食い違いと根拠', schema: discrepancyReportSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  listLeaveTypes: {
    operationId: 'listLeaveTypes',
    method: 'get',
    path: '/leave-types',
    summary: '休暇種別の一覧を取得する',
    tags: ['schedule'],
    security: 'session',
    responses: [
      { status: 200, description: '休暇種別の一覧', schema: leaveTypeListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createLeaveType: {
    operationId: 'createLeaveType',
    method: 'post',
    path: '/leave-types',
    summary: '休暇種別を登録する',
    tags: ['schedule'],
    security: 'session',
    requestBody: createLeaveTypeRequestSchema,
    responses: [
      { status: 201, description: '登録した休暇種別', schema: leaveTypeSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
    ],
  },
  listWorkCycles: {
    operationId: 'listWorkCycles',
    method: 'get',
    path: '/work-cycles',
    summary: '勤務周期の一覧を取得する',
    tags: ['schedule'],
    security: 'session',
    responses: [
      { status: 200, description: '勤務周期の一覧', schema: workCycleListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createWorkCycle: {
    operationId: 'createWorkCycle',
    method: 'post',
    path: '/work-cycles',
    summary: '勤務周期を登録する（週や曜日を前提にしない）',
    tags: ['schedule'],
    security: 'session',
    requestBody: createWorkCycleRequestSchema,
    responses: [
      { status: 201, description: '登録した勤務周期', schema: workCycleSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
      { status: 404, description: '勤務パターンが見つからない', schema: errorResponseSchema },
    ],
  },
  listEmployeeWorkCycles: {
    operationId: 'listEmployeeWorkCycles',
    method: 'get',
    path: '/employee-work-cycles',
    summary: '従業員への勤務周期の割当を一覧する',
    tags: ['schedule'],
    security: 'session',
    query: listEmployeeWorkCyclesQuerySchema,
    responses: [
      { status: 200, description: '割当の一覧', schema: employeeWorkCycleListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  assignWorkCycle: {
    operationId: 'assignWorkCycle',
    method: 'post',
    path: '/employee-work-cycles',
    summary: '従業員へ勤務周期を割り当てる',
    tags: ['schedule'],
    security: 'session',
    requestBody: assignWorkCycleRequestSchema,
    responses: [
      { status: 201, description: '登録した割当', schema: employeeWorkCycleSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      {
        status: 404,
        description: '従業員または勤務周期が見つからない',
        schema: errorResponseSchema,
      },
    ],
  },
  endWorkCycleAssignment: {
    operationId: 'endWorkCycleAssignment',
    method: 'post',
    path: '/employee-work-cycles/{employeeWorkCycleId}/end',
    summary: '勤務周期の割当に終了日を設定する',
    tags: ['schedule'],
    security: 'session',
    pathParameters: [
      { name: 'employeeWorkCycleId', description: '割当の識別子', schema: uuidSchema },
    ],
    requestBody: endWorkCycleAssignmentRequestSchema,
    responses: [
      { status: 200, description: '終了日を設定した割当', schema: employeeWorkCycleSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '割当が見つからない', schema: errorResponseSchema },
      {
        status: 409,
        description: '他の割当と有効期間が重なる',
        schema: errorResponseSchema,
      },
    ],
  },
  generateWorkSchedules: {
    operationId: 'generateWorkSchedules',
    method: 'post',
    path: '/work-schedules/generate',
    summary: '割り当てた勤務周期から期間分の勤務予定を作る',
    tags: ['schedule'],
    security: 'session',
    requestBody: generateWorkSchedulesRequestSchema,
    responses: [
      { status: 200, description: '作成した件数', schema: generateWorkSchedulesResponseSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '従業員が見つからない', schema: errorResponseSchema },
    ],
  },
  listAssignmentContracts: {
    operationId: 'listAssignmentContracts',
    method: 'get',
    path: '/assignment-contracts',
    summary: '雇用元と受入組織のあいだの契約を一覧する',
    tags: ['assignment'],
    security: 'session',
    responses: [
      { status: 200, description: '契約の一覧', schema: assignmentContractListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createAssignmentContract: {
    operationId: 'createAssignmentContract',
    method: 'post',
    path: '/assignment-contracts',
    summary: '契約を登録する',
    tags: ['assignment'],
    security: 'session',
    requestBody: createAssignmentContractRequestSchema,
    responses: [
      { status: 201, description: '登録した契約', schema: assignmentContractSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
      { status: 404, description: '組織が見つからない', schema: errorResponseSchema },
    ],
  },
  listEmployeeAssignments: {
    operationId: 'listEmployeeAssignments',
    method: 'get',
    path: '/employee-assignments',
    summary: '従業員の配属を一覧する',
    tags: ['assignment'],
    security: 'session',
    responses: [
      { status: 200, description: '配属の一覧', schema: employeeAssignmentListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createEmployeeAssignment: {
    operationId: 'createEmployeeAssignment',
    method: 'post',
    path: '/employee-assignments',
    summary: '従業員を勤務先へ配属する',
    tags: ['assignment'],
    security: 'session',
    requestBody: createEmployeeAssignmentRequestSchema,
    responses: [
      { status: 201, description: '登録した配属', schema: employeeAssignmentSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      {
        status: 404,
        description: '従業員・契約・拠点のいずれかが見つからない',
        schema: errorResponseSchema,
      },
      {
        status: 409,
        description: '同じ従業員の配属と期間が重なる',
        schema: errorResponseSchema,
      },
    ],
  },
  endEmployeeAssignment: {
    operationId: 'endEmployeeAssignment',
    method: 'post',
    path: '/employee-assignments/{employeeAssignmentId}/end',
    summary: '配属に終了日を設定する',
    tags: ['assignment'],
    security: 'session',
    pathParameters: [
      { name: 'employeeAssignmentId', description: '配属の識別子', schema: uuidSchema },
    ],
    requestBody: endEmployeeAssignmentRequestSchema,
    responses: [
      { status: 200, description: '終了日を設定した配属', schema: employeeAssignmentSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '配属が見つからない', schema: errorResponseSchema },
      {
        status: 409,
        description: '同じ従業員の配属と期間が重なる',
        schema: errorResponseSchema,
      },
    ],
  },
  listUserScopes: {
    operationId: 'listUserScopes',
    method: 'get',
    path: '/user-scopes',
    summary: '利用者ごとの閲覧できる組織を一覧する',
    tags: ['assignment'],
    security: 'session',
    responses: [
      { status: 200, description: '閲覧範囲の一覧', schema: userScopeListSchema },
      unauthorized,
      forbidden,
    ],
  },
  grantUserScope: {
    operationId: 'grantUserScope',
    method: 'post',
    path: '/user-scopes',
    summary: '利用者へ組織の閲覧範囲を与える（外部承認者もこの仕組みで表す）',
    tags: ['assignment'],
    security: 'session',
    requestBody: grantUserScopeRequestSchema,
    responses: [
      { status: 201, description: '与えた閲覧範囲', schema: userScopeSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '利用者または組織が見つからない', schema: errorResponseSchema },
    ],
  },
  listAnomalies: {
    operationId: 'listAnomalies',
    method: 'get',
    path: '/audit/anomalies',
    summary: '打刻・端末・確定の記録から、確認すべき異常を根拠つきで一覧する',
    tags: ['audit'],
    security: 'session',
    query: listAnomaliesQuerySchema,
    responses: [
      { status: 200, description: '検出した異常', schema: anomalyListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  listWebhookDeliveries: {
    operationId: 'listWebhookDeliveries',
    method: 'get',
    path: '/webhook-deliveries',
    summary: 'Webhook の送信結果を一覧する',
    tags: ['integration'],
    security: 'session',
    responses: [
      { status: 200, description: '送信結果の一覧', schema: webhookDeliveryListSchema },
      unauthorized,
      forbidden,
    ],
  },
  listAuditLogs: {
    operationId: 'listAuditLogs',
    method: 'get',
    path: '/audit/logs',
    summary: '監査記録を一覧する（ワークスペース管理者のみ）',
    tags: ['audit'],
    security: 'session',
    responses: [
      { status: 200, description: '監査記録', schema: auditLogListSchema },
      unauthorized,
      forbidden,
    ],
  },
  exportAttendanceCsv: {
    operationId: 'exportAttendanceCsv',
    method: 'get',
    path: '/exports/attendance.csv',
    summary: '日次の勤怠と集計を CSV で出力する（セッションまたは API キー）',
    tags: ['integration'],
    security: 'sessionOrApiKey',
    query: exportAttendanceQuerySchema,
    responseContentType: 'text/csv',
    responses: [
      { status: 200, description: 'UTF-8 の CSV。1 行目は見出し' },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  exportPayrollCsv: {
    operationId: 'exportPayrollCsv',
    method: 'get',
    path: '/exports/payroll.csv',
    summary: '月次の集計を給与連携向けの汎用 CSV で出力する（セッションまたは API キー）',
    tags: ['integration'],
    security: 'sessionOrApiKey',
    query: exportPayrollQuerySchema,
    responseContentType: 'text/csv',
    responses: [
      { status: 200, description: 'UTF-8 の CSV。1 行目は見出し' },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  importEmployeesCsv: {
    operationId: 'importEmployeesCsv',
    method: 'post',
    path: '/imports/employees',
    summary: '従業員を CSV から取り込む',
    tags: ['integration'],
    security: 'session',
    requestBody: employeeImportCsvSchema,
    requestContentType: 'text/csv',
    responses: [
      { status: 200, description: '取り込み結果', schema: importResultSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  listApiKeys: {
    operationId: 'listApiKeys',
    method: 'get',
    path: '/api-keys',
    summary: 'API キーを一覧する（生の鍵は含まない）',
    tags: ['integration'],
    security: 'session',
    responses: [
      { status: 200, description: 'API キーの一覧', schema: apiKeyListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createApiKey: {
    operationId: 'createApiKey',
    method: 'post',
    path: '/api-keys',
    summary: 'API キーを作る（生の鍵はこの応答でしか返らない）',
    tags: ['integration'],
    security: 'session',
    requestBody: createApiKeyRequestSchema,
    responses: [
      { status: 201, description: '作成した API キー', schema: createApiKeyResponseSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  revokeApiKey: {
    operationId: 'revokeApiKey',
    method: 'post',
    path: '/api-keys/{apiKeyId}/revoke',
    summary: 'API キーを失効させる',
    tags: ['integration'],
    security: 'session',
    pathParameters: [{ name: 'apiKeyId', description: 'API キーの識別子', schema: uuidSchema }],
    responses: [
      { status: 200, description: '失効した API キー', schema: apiKeySchema },
      unauthorized,
      forbidden,
      { status: 404, description: 'API キーが見つからない', schema: errorResponseSchema },
    ],
  },
  listWebhookEndpoints: {
    operationId: 'listWebhookEndpoints',
    method: 'get',
    path: '/webhook-endpoints',
    summary: 'Webhook の送信先を一覧する',
    tags: ['integration'],
    security: 'session',
    responses: [
      { status: 200, description: '送信先の一覧', schema: webhookEndpointListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createWebhookEndpoint: {
    operationId: 'createWebhookEndpoint',
    method: 'post',
    path: '/webhook-endpoints',
    summary: 'Webhook の送信先を登録する（署名用の秘密はこの応答でしか返らない）',
    tags: ['integration'],
    security: 'session',
    requestBody: createWebhookEndpointRequestSchema,
    responses: [
      {
        status: 201,
        description: '登録した送信先',
        schema: createWebhookEndpointResponseSchema,
      },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  listLeaveTypeSettings: {
    operationId: 'listLeaveTypeSettings',
    method: 'get',
    path: '/leave-type-settings',
    summary: '休暇種別の取得単位と失効の設定を一覧する',
    tags: ['leave'],
    security: 'session',
    responses: [
      { status: 200, description: '休暇種別の設定', schema: leaveTypeSettingsListSchema },
      unauthorized,
      forbidden,
    ],
  },
  updateLeaveType: {
    operationId: 'updateLeaveType',
    method: 'patch',
    path: '/leave-type-settings/{leaveTypeId}',
    summary: '休暇種別の取得単位と失効を設定する',
    tags: ['leave'],
    security: 'session',
    pathParameters: [{ name: 'leaveTypeId', description: '休暇種別の識別子', schema: uuidSchema }],
    requestBody: updateLeaveTypeRequestSchema,
    responses: [
      { status: 200, description: '直した休暇種別', schema: leaveTypeSettingsSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '休暇種別が見つからない', schema: errorResponseSchema },
    ],
  },
  listLeaveLedger: {
    operationId: 'listLeaveLedger',
    method: 'get',
    path: '/leave-ledger',
    summary: '休暇台帳の記録を一覧する',
    tags: ['leave'],
    security: 'session',
    query: listLeaveLedgerQuerySchema,
    responses: [
      { status: 200, description: '台帳の記録', schema: leaveLedgerListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  listLeaveBalances: {
    operationId: 'listLeaveBalances',
    method: 'get',
    path: '/leave-balances',
    summary: '休暇の残数を、台帳から組み立てて返す',
    tags: ['leave'],
    security: 'session',
    query: listLeaveBalancesQuerySchema,
    responses: [
      { status: 200, description: '休暇種別ごとの残数', schema: leaveBalanceListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  grantLeave: {
    operationId: 'grantLeave',
    method: 'post',
    path: '/leave-ledger/grants',
    summary: '休暇を付与する',
    tags: ['leave'],
    security: 'session',
    requestBody: grantLeaveRequestSchema,
    responses: [
      { status: 201, description: '積んだ記録', schema: leaveLedgerEntrySchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '従業員か休暇種別が見つからない', schema: errorResponseSchema },
    ],
  },
  adjustLeave: {
    operationId: 'adjustLeave',
    method: 'post',
    path: '/leave-ledger/adjustments',
    summary: '休暇の残数を手当てする',
    tags: ['leave'],
    security: 'session',
    requestBody: adjustLeaveRequestSchema,
    responses: [
      { status: 201, description: '積んだ記録', schema: leaveLedgerEntrySchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
      { status: 404, description: '従業員か休暇種別が見つからない', schema: errorResponseSchema },
    ],
  },
  reverseLeaveEntry: {
    operationId: 'reverseLeaveEntry',
    method: 'post',
    path: '/leave-ledger/{leaveLedgerEntryId}/reverse',
    summary: '台帳の記録を取り消す（元の行は消さず、打ち消す行を足す）',
    tags: ['leave'],
    security: 'session',
    pathParameters: [
      { name: 'leaveLedgerEntryId', description: '台帳の記録の識別子', schema: uuidSchema },
    ],
    requestBody: reverseLeaveEntryRequestSchema,
    responses: [
      { status: 201, description: '打ち消す記録', schema: leaveLedgerEntrySchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
      { status: 404, description: '記録が見つからない', schema: errorResponseSchema },
    ],
  },
  listRequestTypes: {
    operationId: 'listRequestTypes',
    method: 'get',
    path: '/request-types',
    summary: '申請種別を一覧する',
    tags: ['request'],
    security: 'session',
    responses: [
      { status: 200, description: '申請種別の一覧', schema: requestTypeListSchema },
      unauthorized,
      forbidden,
    ],
  },
  createRequestType: {
    operationId: 'createRequestType',
    method: 'post',
    path: '/request-types',
    summary: '申請種別を作る',
    tags: ['request'],
    security: 'session',
    requestBody: createRequestTypeRequestSchema,
    responses: [
      { status: 201, description: '作った申請種別', schema: requestTypeSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
    ],
  },
  updateRequestType: {
    operationId: 'updateRequestType',
    method: 'patch',
    path: '/request-types/{requestTypeId}',
    summary: '申請種別を直す（提出済みの申請の段数は動かない）',
    tags: ['request'],
    security: 'session',
    pathParameters: [
      { name: 'requestTypeId', description: '申請種別の識別子', schema: uuidSchema },
    ],
    requestBody: updateRequestTypeRequestSchema,
    responses: [
      { status: 200, description: '直した申請種別', schema: requestTypeSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '申請種別が見つからない', schema: errorResponseSchema },
    ],
  },
  listEmployeeRequests: {
    operationId: 'listEmployeeRequests',
    method: 'get',
    path: '/employee-requests',
    summary: '申請を一覧する',
    tags: ['request'],
    security: 'session',
    query: listEmployeeRequestsQuerySchema,
    responses: [
      { status: 200, description: '申請の一覧', schema: employeeRequestListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  submitEmployeeRequest: {
    operationId: 'submitEmployeeRequest',
    method: 'post',
    path: '/employee-requests',
    summary: '申請を出す（段数は提出時の定義から写す）',
    tags: ['request'],
    security: 'session',
    requestBody: submitEmployeeRequestRequestSchema,
    responses: [
      { status: 201, description: '出した申請', schema: employeeRequestSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '申請種別か従業員が見つからない', schema: errorResponseSchema },
    ],
  },
  decideEmployeeRequest: {
    operationId: 'decideEmployeeRequest',
    method: 'post',
    path: '/employee-requests/{employeeRequestId}/decisions',
    summary: '申請の段を決裁する',
    tags: ['request'],
    security: 'session',
    pathParameters: [
      { name: 'employeeRequestId', description: '申請の識別子', schema: uuidSchema },
    ],
    requestBody: decideEmployeeRequestRequestSchema,
    responses: [
      { status: 200, description: '決裁後の申請', schema: employeeRequestSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
      { status: 404, description: '申請が見つからない', schema: errorResponseSchema },
    ],
  },
  resubmitEmployeeRequest: {
    operationId: 'resubmitEmployeeRequest',
    method: 'post',
    path: '/employee-requests/{employeeRequestId}/resubmissions',
    summary: '差し戻された申請を出し直す',
    tags: ['request'],
    security: 'session',
    pathParameters: [
      { name: 'employeeRequestId', description: '申請の識別子', schema: uuidSchema },
    ],
    requestBody: resubmitEmployeeRequestRequestSchema,
    responses: [
      { status: 200, description: '出し直した申請', schema: employeeRequestSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      conflict,
      { status: 404, description: '申請が見つからない', schema: errorResponseSchema },
    ],
  },
  cancelEmployeeRequest: {
    operationId: 'cancelEmployeeRequest',
    method: 'post',
    path: '/employee-requests/{employeeRequestId}/cancellation',
    summary: '申請を取り下げる',
    tags: ['request'],
    security: 'session',
    pathParameters: [
      { name: 'employeeRequestId', description: '申請の識別子', schema: uuidSchema },
    ],
    responses: [
      { status: 200, description: '取り下げた申請', schema: employeeRequestSchema },
      unauthorized,
      forbidden,
      conflict,
      { status: 404, description: '申請が見つからない', schema: errorResponseSchema },
    ],
  },
  listPeriodSummaries: {
    operationId: 'listPeriodSummaries',
    method: 'get',
    path: '/period-summaries',
    summary: '週・清算期間・変形労働の対象期間の集計を一覧する',
    tags: ['approval'],
    security: 'sessionOrApiKey',
    query: listPeriodSummariesQuerySchema,
    responses: [
      { status: 200, description: '期間の集計', schema: periodSummaryListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  listMonthlySummaries: {
    operationId: 'listMonthlySummaries',
    method: 'get',
    path: '/monthly-summaries',
    summary: '月次の集計を一覧する（締めた月は締めた時点の値も返す）',
    tags: ['approval'],
    security: 'sessionOrApiKey',
    query: listMonthlySummariesQuerySchema,
    responses: [
      { status: 200, description: '月次の集計', schema: monthlySummaryListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  listClosingReadiness: {
    operationId: 'listClosingReadiness',
    method: 'get',
    path: '/monthly-closings/readiness',
    summary: '締める前に残っているものを一覧する',
    tags: ['approval'],
    security: 'session',
    query: listMonthlySummariesQuerySchema,
    responses: [
      { status: 200, description: '締め前の確認', schema: closingReadinessListSchema },
      invalidRequest,
      unauthorized,
      forbidden,
    ],
  },
  recalculateAttendance: {
    operationId: 'recalculateAttendance',
    method: 'post',
    path: '/attendance/recalculations',
    summary: '日次の集計をやり直す（締めた月は動かさない）',
    tags: ['attendance'],
    security: 'session',
    requestBody: recalculateAttendanceRequestSchema,
    responses: [
      { status: 200, description: 'やり直した結果', schema: recalculateAttendanceResponseSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '従業員が見つからない', schema: errorResponseSchema },
    ],
  },
  listAbandonedDeliveries: {
    operationId: 'listAbandonedDeliveries',
    method: 'get',
    path: '/webhook-deliveries/abandoned',
    summary: '諦めた通知を一覧する（行は消えていない）',
    tags: ['integration'],
    security: 'session',
    responses: [
      { status: 200, description: '諦めた通知', schema: abandonedDeliveryListSchema },
      unauthorized,
      forbidden,
    ],
  },
  requeueAbandonedDelivery: {
    operationId: 'requeueAbandonedDelivery',
    method: 'post',
    path: '/webhook-deliveries/abandoned/{outboxId}/requeue',
    summary: '諦めた通知を、もう一度送信待ちへ戻す',
    tags: ['integration'],
    security: 'session',
    pathParameters: [{ name: 'outboxId', description: '送信待ちの識別子', schema: uuidSchema }],
    responses: [
      { status: 204, description: '送信待ちへ戻した' },
      unauthorized,
      forbidden,
      { status: 404, description: '諦めた通知が見つからない', schema: errorResponseSchema },
    ],
  },
  revokeUserSessions: {
    operationId: 'revokeUserSessions',
    method: 'post',
    path: '/users/{userId}/sessions/revoke',
    summary: '管理者が、利用者のセッションをすべて終わらせる（退職・端末の紛失）',
    tags: ['auth'],
    security: 'session',
    pathParameters: [{ name: 'userId', description: '利用者の識別子', schema: uuidSchema }],
    responses: [
      { status: 200, description: '終わらせた数', schema: revokedUserSessionsSchema },
      unauthorized,
      forbidden,
      { status: 404, description: '利用者が見つからない', schema: errorResponseSchema },
    ],
  },
  resetUserPassword: {
    operationId: 'resetUserPassword',
    method: 'post',
    path: '/users/{userId}/password',
    summary: '管理者が、利用者のパスワードを再設定する（本人が入れなくなったとき）',
    tags: ['auth'],
    security: 'session',
    pathParameters: [{ name: 'userId', description: '利用者の識別子', schema: uuidSchema }],
    requestBody: resetUserPasswordRequestSchema,
    responses: [
      { status: 200, description: '終わらせたセッションの数', schema: revokedUserSessionsSchema },
      invalidRequest,
      unauthorized,
      forbidden,
      { status: 404, description: '利用者が見つからない', schema: errorResponseSchema },
    ],
  },
} as const satisfies Record<string, OperationContract>;

export type OperationId = keyof typeof operations;

export const operationList: readonly OperationContract[] = Object.values(operations);
